global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'envoy'
    metrics_path: /stats/prometheus
    static_configs:
    - targets: ['proxy:8111']
