{
 "title": "Envoy Summary",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "envoy_cluster_upstream_cx_active",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_upstream_cx_active"
    }
   ]
  },
  {
   "title": "app_cluster envoy_cluster_upstream_rq_time_bucket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"app_cluster\"}[15s])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"app_cluster\"}[15s])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"app_cluster\"}[15s])) by (le))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "envoy_cluster_upstream_rq_timeout",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_rq_timeout[15s])"
    }
   ]
  },
  {
   "title": "envoy_cluster_external_upstream_rq_xx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_cluster_external_upstream_rq_xx[15s])"
    }
   ]
  }
 ]
}